language: go
go:
  - 1.7
  - 1.6
  - 1.5
  - 1.4
install: 
  - go get golang.org/x/crypto/pbkdf2 
  - go get github.com/howeyc/gopass
  - go get github.com/spf13/pflag
  - go get github.com/spf13/cobra/cobra